# Generated by Django 4.2.23 on 2025-12-15 12:50

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'branches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'car_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=12, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year_made', models.SmallIntegerField()),
                ('mileage', models.IntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarStatuses',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'car_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('passport', models.CharField(max_length=20, unique=True)),
                ('dl_number', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('payment', models.CharField(max_length=12)),
                ('rent_period', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractStatuses',
            fields=[
                ('cstatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'contract_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=20)),
                ('service_date', models.DateField()),
                ('mileage_at', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
    ]
